os: linux
dist: xenial
language: go

services:
  - docker

jobs:
  fast_finish: true
  include:
    - name: MySQL5.7-1.17.x
      go: 1.17.x
      env:
        - GOU_TEST_API_ROOT="$TRAVIS_BUILD_DIR/app/apis" GOU_TEST_MOD_ROOT="$TRAVIS_BUILD_DIR/app/models" GOU_TEST_PLG_ROOT="$HOME/data/gou-unit/plugins" GOU_TEST_PLG_LOG="$HOME/data/gou-unit/logs" GOU_TEST_DSN="root:123456@tcp(127.0.0.1:3306)/xun?charset=utf8mb4&parseTime=True&loc=Local" GOT_TEST_AES_KEY="^*aNBue!loLTTiP*4i&BSK7s#QRbe0^g" CODECOV_TOKEN='3683ff24-57de-4282-a5da-de0799f04969'
      before_install:
        - unit/service.sh mysql5.7 # Start MySQL 5.7 service
    - name: MySQL5.6-1.17.x
      go: 1.17.x
      env:
        - GOU_TEST_API_ROOT="$TRAVIS_BUILD_DIR/app/apis" GOU_TEST_MOD_ROOT="$TRAVIS_BUILD_DIR/app/models" GOU_TEST_PLG_ROOT="$HOME/data/gou-unit/plugins" GOU_TEST_PLG_LOG="$HOME/data/gou-unit/logs" GOU_TEST_DSN="root:123456@tcp(127.0.0.1:3307)/xun?charset=utf8mb4&parseTime=True&loc=Local" GOT_TEST_AES_KEY="^*aNBue!loLTTiP*4i&BSK7s#QRbe0^g" CODECOV_TOKEN='3683ff24-57de-4282-a5da-de0799f04969'
      before_install:
        - unit/service.sh mysql5.6 # Start MySQL 5.6 service
git:
  depth: 10
install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

go_import_path: github.com/yaoapp/gou

script:
  - export
  - make vet
  - make fmt-check
  - make misspell-check
  - make plugin
  - make migrate
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
