name: Unit-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.17]
        db: [MySQL8.0, MySQL5.7, Postgres9.6, Postgres14, SQLite3]
    env:
      DSN: default
    steps:
      - name: Setup ${{ matrix.db }}
        uses: ./.github/actions/setup-db
        with:
          kind: "gou"
          user: "gou"
          password: "123456"

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo $DSN
          export
