name: Unit-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CODECOV_TOKEN: 3683ff24-57de-4282-a5da-de0799f04969
  GOT_TEST_AES_KEY: "^*aNBue!loLTTiP*4i&BSK7s#QRbe0^g"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.17]
        db: [MySQL8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ${{ matrix.db }}
        uses: ./.github/actions/setup-db
        with:
          kind: "${{ matrix.db }}"
          db: "gou"
          user: "gou"
          password: "123456"

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go Tools
        run: |
          if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
          if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
          if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

      - name: Setup ENV
        run: |
          echo "GOU_TEST_DSN=$DSN" >> $GITHUB_ENV
          echo "GOU_TEST_DB_DRIVER=$DB_DRIVER" >> $GITHUB_ENV
          echo "GOU_TEST_API_ROOT=$GITHUB_WORKSPACE/app/apis" >> $GITHUB_ENV
          echo "GOU_TEST_FLW_ROOT=$GITHUB_WORKSPACE/app/flows" >> $GITHUB_ENV
          echo "GOU_TEST_MOD_ROOT=$GITHUB_WORKSPACE/app/models" >> $GITHUB_ENV
          echo "GOU_TEST_PLG_ROOT=$HOME/data/gou-unit/plugins" >> $GITHUB_ENV
          echo "GOU_TEST_PLG_LOG=$HOME/data/gou-unit/logs" >> $GITHUB_ENV

      - name: Run Test
        run: |
          make vet
          make fmt-check
          make misspell-check
          make plugin
          make migrate
          make test
