name: Unit-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.17]
        db: [MySQL8.0, MySQL5.7, Postgres9.6, Postgres14, SQLite3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ${{ matrix.db }}
        uses: ./.github/actions/setup-db
        with:
          kind: "${{ matrix.db }}"
          db: "gou"
          user: "gou"
          password: "123456"

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run Test
        run: |
          # Setup ENV
          GOU_TEST_DSN=$DSN
          GOU_TEST_API_ROOT="$GITHUB_WORKSPACE/app/apis"
          GOU_TEST_FLW_ROOT="$GITHUB_WORKSPACE/app/flows"
          GOU_TEST_MOD_ROOT="$GITHUB_WORKSPACE/app/models"
          GOU_TEST_PLG_ROOT="$HOME/data/gou-unit/plugins"
          GOU_TEST_PLG_LOG="$HOME/data/gou-unit/logs"

          # RUN Test
          echo $GOU_TEST_DSN
          echo $GOU_TEST_API_ROOT
          echo $GOU_TEST_PLG_ROOT
          export
